version: '3'
services:
  app:
    image: 8base/docker-amazonlinux-node:node8
    volumes:
      - .:/srv/
    tty: true
    command: bash
    working_dir: /srv
    environment:
      - CI=true
  localstack:
    image: "localstack/localstack"
    ports:
      - 4567-4583:4567-4583
      - 8080:8080
    environment:
      - SERVICES=s3
