version: 2
jobs:
  build:
    docker:
      - image: 8base/docker-amazonlinux-node:node8
      - image: "localstack/localstack"
        ports:
          - 4567-4583:4567-4583
          - 8080:8080
        environment:
          - SERVICES=s3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: make

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: make localstack
      - run: make test
      - run: make build
      - run: yum install tar -y
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: sudo pip install awscli
      - run:
          command: make deploy
          no_output_timeout: 1800

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
