version: 2
jobs:
  build:
    docker:
      - image: 8base/docker-amazonlinux-node:node8
      - image: "localstack/localstack"
        ports:
          - 4567-4583:4567-4583
          - 8080:8080
        environment:
          - SERVICES=s3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: make
      - run: make localstack

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: make test
      - run: make build
  provision:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: sudo pip install awscli
      - run: make test -C deployment
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - provision